### ISSUE TITLE
Is this the correct way to unsubscribe?

### ISSUE THREAD

**Issue by dminkovsky** [relay-tools/react-relay-mutation#160]
I found this repo trying to figure out how to use `commitMutation` with Hooks

* `commitMutation` returns a subscription that should be handled.
* The Hooks API lets you do this with `useEffect`
* `useEffect` seems wrong for this use-case.
* This repo uses `useCallback` and instead of handling the subscription, uses `isMounted`, which seems wrong too.

Is this the Hooks way?

**Comment by dminkovsky** [comment]
Oh I see there is a PR

**Comment by dminkovsky** [comment]
Sorry, got confused there for a second :)

**Comment by dminkovsky** [comment]
[`useRef`](https://medium.com/@rajeshnaroth/writing-a-react-hook-to-cancel-promises-when-a-component-unmounts-526efabf251f)?

**Comment by taion** [comment]
I'm not sure what you mean by `subscription`. Did you look at the `useMutation` hook here?

**Comment by dminkovsky** [comment]
By "subscription" I am referring to the [dispose method](https://github.com/facebook/relay/blob/0c048a162bc7e4845bec83d506ce61e1fd9c0644/packages/relay-runtime/mutations/commitRelayModernMutation.js#L113) returned by `commitMutation`. In this package it is not used. An isMounted check is used instead.

**Comment by taion** [comment]
Are you using a network layer where disposing that subscription actually does something? It seems like an "is mounted" check would be roughly equivalent, no?

**Comment by dminkovsky** [comment]
I'm sorry, I titled the question poorly. It should be something like "Is this the correct way to unsubscribe?" I understand that this works, too.

**Comment by taion** [comment]
Ah, yes – I think that's right. You can either use an `isMounted` check in your callback handler, or you can use the mutation state properties with `useEffect`. Both work just fine, I think.
